#МандаинГЕЙ100%
#Плагин написан самым крутым в мире Паримэком, круче Паримэка вы не найдёте ни где!
#Ну и был написан для сервера страх эмси на свой страх и риск используйте этот плагин так как Паримэк бальной и мог в него вшить всякую хуйню
#Ну а если ты до сих пор в танке, то для этого плагина не нужен конфиг воообще, а так только для хранения сообщения о том что 'ебать ты юра нахуя портал поставил!' Что то типо этого поэтому иди спи
#Тут один единственный параметр в конфиге
#Это изменение сообщения на своё
message:
  enderportalframeplace: 'Ну и нахуя ты меня тут поставил !?'