name: AntiEndPortalFrame
version: '${project.version}'
main: strictmcru.antiendportalframe.antiendportalframe.AntiEndPortalFrame
api-version: 1.16
softdepend: [ StrictAPI ]
authors: [ parimek, StrictMC ]
description: Anti place End Portal Frame! End Portal Frame replace to End Portal
website: https://strictmc.ru
